services:
  - type: web
    name: arapstore-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Sto:Kipkorir%2E1595@cysec.jyxmnlp.mongodb.net/arapstore?retryWrites=true&w=majority&appName=CySec
      - key: NODE_ENV
        value: production
    repo: https://github.com/yourusername/arapstore
    autoDeploy: true

  - type: web
    name: arapstore-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: client/build
    repo: https://github.com/yourusername/arapstore
    autoDeploy: true
